services:
  - type: web
    name: evolution-api
    env: docker
    region: frankfurt
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz

    envVars:
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: evolutionDB
          property: connectionString
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolutionDB
          property: connectionString
      - key: PORT
        value: "8080"
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        fromService:
          name: evolution-redis
          type: keyvalue
          property: connectionString
      - key: SERVER_TYPE
        value: http
      - key: CORS_ORIGIN
        value: "*"
      - key: AUTHENTICATION_API_KEY
        value: ab8rmpU9V4T4XwwfAbUWg1N4z1evOgZ4

  - type: keyvalue
    name: evolution-redis
    region: frankfurt
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: evolutionDB
    region: frankfurt
    plan: free
