services:
  - type: web
    name: evolution-api
    env: docker
    region: frankfurt
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz

    envVars:
      # Banco de dados principal
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: evolutionDB
          property: connectionString

      # Porta do servidor
      - key: PORT
        value: 8080

      # Configurações de Redis (usando o Redis gerenciado pela Render)
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        fromService:
          type: redis
          name: evolution-redis
          property: connectionString

      # Outras variáveis essenciais (pode expandir depois conforme seu .env)
      - key: SERVER_TYPE
        value: http
      - key: SERVER_PORT
        value: 8080
      - key: CORS_ORIGIN
        value: "*"
      - key: AUTHENTICATION_API_KEY
        value: ab8rmpU9V4T4XwwfAbUWg1N4z1evOgZ4
      - key: LANGUAGE
        value: en

databases:
  - name: evolutionDB
    region: frankfurt
    plan: free

redis:
  - name: evolution-redis
    region: frankfurt
    plan: free
