services:
  - type: web
    name: evolution-api
    env: docker
    region: frankfurt # define a região (mesma do banco para menor latência)
    plan: free
    branch: main
    numInstances: 1 # número de instâncias do serviço
    healthCheckPath: /healthz # endpoint de checagem de saúde

    envVars:
      - key: DATABASE_PROVIDER
        value: postgresql # especifica o provedor do banco (PostgreSQL)
      - key: DATABASE_URL
        # URL de conexão completa (usuário, senha, host, porta, nome do banco) do PostgreSQL no Render
        fromDatabase:
          name: evolutionDB
          property: connectionString
      - key: PORT
        value: 8080 # porta em que a aplicação será executada (padrão 8080)

databases:
  - name: evolutionDB
    region: frankfurt # banco de dados na mesma região do serviço
    plan: free # plano gratuito do banco
