services:
  - type: web
    name: evolution-api
    env: docker
    region: frankfurt # você pode trocar para sua região preferida
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      # 1) Provider para rodar as migrations corretas
      - key: DATABASE_PROVIDER
        value: postgresql

      # 2) Conexão ao banco (Render injeta host, user, senha, porta e database)
      - key: DB_HOST
        fromDatabase:
          name: evolutionDB
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: evolutionDB
          property: database
      - key: DB_PORT
        fromDatabase:
          name: evolutionDB
          property: port
      - key: DB_USER
        fromDatabase:
          name: evolutionDB
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: evolutionDB
          property: password

      # 3) URL completa para o Prisma (já monta tudo que precisa)
      - key: DATABASE_URL
        fromDatabase:
          name: evolutionDB
          property: connectionString

      # 4) Porta que o seu app expõe
      - key: PORT
        value: "8080"

databases:
  - name: evolutionDB
    region: frankfurt
    plan: free
