services:
  # 1) Serviço Web da Evolution API
  - type: web
    name: evolution-api
    env: docker
    region: frankfurt # mesmo da base e do Redis
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz

    envVars:
      # Banco PostgreSQL
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: evolutionDB
          property: connectionString

      # Porta
      - key: PORT
        value: 8080

      # Redis (Key Value)
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        fromService:
          name: evolution-redis
          type: keyvalue
          property: connectionString

      # Outras variáveis essenciais (adicione conforme seu .env)
      - key: SERVER_TYPE
        value: http
      - key: CORS_ORIGIN
        value: "*"
      - key: AUTHENTICATION_API_KEY
        value: ab8rmpU9V4T4XwwfAbUWg1N4z1evOgZ4

  # 2) Serviço Redis gerenciado pela Render
  - type: keyvalue # alias 'redis' também funciona
    name: evolution-redis
    region: frankfurt
    plan: free
    ipAllowList: # obrigatório para Key Value
      - source: 0.0.0.0/0
        description: everywhere

# 3) Banco de dados PostgreSQL
databases:
  - name: evolutionDB
    region: frankfurt
    plan: free
